name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-test-backend:
    name: Build & Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Run linter (optional)
        run: npx eslint . || true  # You can remove this if you don’t use ESLint

  deploy:
    name: Deploy to Render
    needs: build-and-test-backend
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Backend to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_BACKEND }}

      - name: Deploy Frontend to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_FRONTEND }}

      - name: Deploy Mail Service to Render
        run: curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK_MAILSERVICE }}
